Archivo arreglados
riduarte/project-McBackEnd pull request #2
Opened 2020-09-03 09:50 UTC by riduarte

2020-09-03 09:54 UTC, JulioSau approved these changes

2020-09-04 09:31 UTC, JimenaEB requested changes

2020-09-04 09:31 UTC, JimenaEB commented on src/main.py
> +    return "You have delete cooker"
Hay que devolver el cooker que borramos

2020-09-04 09:31 UTC, JimenaEB commented on src/models.py
> +            "password":self.password,
Si es que...

2020-09-04 09:31 UTC, JimenaEB commented on src/models.py
> +            if key != "id":
is active tampoco se debería poder modificar

2020-09-04 09:31 UTC, JimenaEB commented on src/models.py
> +        db.session.commit()
y add?

2020-09-04 09:31 UTC, JimenaEB commented on src/models.py
> +            "is_active":self.is_active
no os hace falta is_active

2020-09-04 09:31 UTC, JimenaEB commented on src/models.py
> +            if key != "id":
ni la marca ni el active deberían cambiarse

2020-09-04 09:31 UTC, JimenaEB commented on src/utils.py
> +def validation_email(cooker_email):
Aquí puedes añadir lo que ha explicado Andrea

2020-09-14 09:04 UTC, closed without merging